const PI = 3.14159265359;
const MAX_DIRECTIONAL_LIGHTS = 2;
const MAX_POINT_LIGHTS = 64;

const SHADER_QUALITY_LOW = 1;
const SHADER_QUALITY_NORMAL = 2;

const SHADOW_FILTERING_OFF = 0;
const SHADOW_FILTERING_PCF = 1;
const SHADOW_FILTERING_PCSS_PCF = 2;
