name: Build Server
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Installing Dependencies
        working-directory: server
        run: bun install
      - name: Verify Lint
        working-directory: server
        run: bun lint
      - name: Build Server
        working-directory: server
        run: bun run build
      - name: Sharing Executables
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist
