name: Build Game
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  build-game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Installing Dependencies
        working-directory: game
        run: npm ci
      - name: Verify Lint
        working-directory: game
        run: npm run lint
      - name: Build Game
        working-directory: game
        run: npm run build
      - name: Share Game Bundle
        uses: actions/upload-artifact@v4
        with:
          name: game-bundle
          path: game/build/**/*
