name: Dev Build
on:
  push:
    tags:
      - v**-* # Will trigger on all "open" tags, eg. v0.9.0-dev or v1.0.0-alpha, not triggering on "closed" tags like v1.0.0

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: Get Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: server
      - name: Installing Dependencies
        working-directory: server
        run: npm ci
      - name: Verify Lint
        working-directory: server
        run: npm run lint
      - name: Build Server
        working-directory: server
        run: npm run build
      - name: Pack Server Executables
        working-directory: server
        run: npm run pack
      - name: Rename Executables
        working-directory: server/dist
        run: for file in *; do mv "$file" $(echo "$file" | sed -E "s/war2-server-(.+)/War2-Server-${{ steps.version.outputs.current-version }}-\1/"); done
      - name: Sharing Executables
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist

  build-game:
    name: Build Game
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: game/package-lock.json
      - name: Installing Dependencies
        working-directory: game
        run: npm ci
      - name: Verify Lint
        working-directory: game
        run: npm run lint
      - name: Build Game
        working-directory: game
        run: npm run build
      - name: Share Game Bundle
        uses: actions/upload-artifact@v4
        with:
          name: game-bundle
          path: game/build/
      - name: Build Windows Binaries
        working-directory: game
        run: npm run electron-build-windows
      - name: Sharing Executables
        uses: actions/upload-artifact@v4
        with:
          name: game-dist
          path: game/dist/*.exe

  generate-release:
    name: Generate Release
    needs: [build-server, build-game]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency: 
      group: "pages"
      cancel-in-progress: false
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Download Server Binaries
        uses: actions/download-artifact@v4
        with:
          name: server-dist
          path: './binaries/'
      - name: Download Game Binaries
        uses: actions/download-artifact@v4
        with:
          name: game-dist
          path: './binaries/'
      - name: Download Game Bundle
        uses: actions/download-artifact@v4
        with:
          name: game-bundle
          path: './game-bundle/'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: In-Dev ${{ github.ref_name }}
          draft: false
          prerelease: true
          tag_name: ${{ github.ref_name }}
          files: ./binaries/*
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload Build to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './game/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
