name: Server Lint
on:
  push:
    branches: ["master", "dev"]

jobs:
  lint-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Switch to Server
        run: cd server
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Installing Requirements
        run: npm ci
      - name: Verify Lint
        run: npm run lint
