name: Build for Closed Versions
on:
  push:
    tags:
      - "v0.[0-9]+.[0-9]+" # Will trigger on all closed tags, eg. v1.9.0 or v0.87.12, not triggering on open tags like v0.12.0-rc4 or v1.0.0-rc1
      - "!v0.[0-9]+.[0-9]+-*"

jobs:
  build-project:
    uses: ./.github/workflows/dispatch-build.yaml
    with:
      branch: master

  create-release:
    uses: ./.github/workflows/create-release.yaml
    needs: [build-project]
    with:
      branch: master
      prerelease: true
