name: Build for Stable Versions
on:
  push:
    tags:
      - "v[1-9][0-9]*.[0-9]+.[0-9]+" # Will trigger on all closed tags starting with a non-zero number, eg. v1.0.0 or v54.6.135, not triggering on tags like v0.97.1
      - "!v[1-9][0-9]*.[0-9]+.[0-9]+-*"

jobs:
  build-project:
    uses: ./.github/workflows/dispatch-build.yaml
    with:
      branch: master
      node-version: 22.x

  create-release:
    uses: ./.github/workflows/create-release.yaml
    needs: [build-project]
    with:
      branch: master
      prerelease: false
